/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MailRouteImport } from './routes/mail'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as WhiteboardsRouteImport } from './routes/whiteboards'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as AreasFolderRouteImport } from './routes/areas.$folder'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsFolderRouteImport } from './routes/projects.$folder'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesFolderRouteImport } from './routes/resources.$folder'
import { Route as ApiMailSplatRouteImport } from './routes/api.mail.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const WhiteboardsRoute = WhiteboardsRouteImport.update({
  id: '/whiteboards',
  path: '/whiteboards',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AreasRoute,
} as any)
const AreasFolderRoute = AreasFolderRouteImport.update({
  id: '/$folder',
  path: '/$folder',
  getParentRoute: () => AreasRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsFolderRoute = ProjectsFolderRouteImport.update({
  id: '/$folder',
  path: '/$folder',
  getParentRoute: () => ProjectsRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesFolderRoute = ResourcesFolderRouteImport.update({
  id: '/$folder',
  path: '/$folder',
  getParentRoute: () => ResourcesRoute,
} as any)
const ApiMailSplatRoute = ApiMailSplatRouteImport.update({
  id: '/api/mail/$',
  path: '/api/mail/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/areas': typeof AreasRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/capture': typeof CaptureRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/tasks': typeof TasksRoute
  '/whiteboards': typeof WhiteboardsRoute
  '/areas/$folder': typeof AreasFolderRoute
  '/projects/$folder': typeof ProjectsFolderRoute
  '/resources/$folder': typeof ResourcesFolderRoute
  '/areas/': typeof AreasIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/mail/$': typeof ApiMailSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/calendar': typeof CalendarRoute
  '/capture': typeof CaptureRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/tasks': typeof TasksRoute
  '/whiteboards': typeof WhiteboardsRoute
  '/areas/$folder': typeof AreasFolderRoute
  '/projects/$folder': typeof ProjectsFolderRoute
  '/resources/$folder': typeof ResourcesFolderRoute
  '/areas': typeof AreasIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/api/mail/$': typeof ApiMailSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/areas': typeof AreasRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/capture': typeof CaptureRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/tasks': typeof TasksRoute
  '/whiteboards': typeof WhiteboardsRoute
  '/areas/$folder': typeof AreasFolderRoute
  '/projects/$folder': typeof ProjectsFolderRoute
  '/resources/$folder': typeof ResourcesFolderRoute
  '/areas/': typeof AreasIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/mail/$': typeof ApiMailSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/areas'
    | '/calendar'
    | '/capture'
    | '/inbox'
    | '/login'
    | '/mail'
    | '/projects'
    | '/resources'
    | '/tasks'
    | '/whiteboards'
    | '/areas/$folder'
    | '/projects/$folder'
    | '/resources/$folder'
    | '/areas/'
    | '/projects/'
    | '/resources/'
    | '/api/mail/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/calendar'
    | '/capture'
    | '/inbox'
    | '/login'
    | '/mail'
    | '/tasks'
    | '/whiteboards'
    | '/areas/$folder'
    | '/projects/$folder'
    | '/resources/$folder'
    | '/areas'
    | '/projects'
    | '/resources'
    | '/api/mail/$'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/areas'
    | '/calendar'
    | '/capture'
    | '/inbox'
    | '/login'
    | '/mail'
    | '/projects'
    | '/resources'
    | '/tasks'
    | '/whiteboards'
    | '/areas/$folder'
    | '/projects/$folder'
    | '/resources/$folder'
    | '/areas/'
    | '/projects/'
    | '/resources/'
    | '/api/mail/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  AreasRoute: typeof AreasRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CaptureRoute: typeof CaptureRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MailRoute: typeof MailRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  TasksRoute: typeof TasksRoute
  WhiteboardsRoute: typeof WhiteboardsRoute
  ApiMailSplatRoute: typeof ApiMailSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whiteboards': {
      id: '/whiteboards'
      path: '/whiteboards'
      fullPath: '/whiteboards'
      preLoaderRoute: typeof WhiteboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof AreasRoute
    }
    '/areas/$folder': {
      id: '/areas/$folder'
      path: '/$folder'
      fullPath: '/areas/$folder'
      preLoaderRoute: typeof AreasFolderRouteImport
      parentRoute: typeof AreasRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$folder': {
      id: '/projects/$folder'
      path: '/$folder'
      fullPath: '/projects/$folder'
      preLoaderRoute: typeof ProjectsFolderRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/$folder': {
      id: '/resources/$folder'
      path: '/$folder'
      fullPath: '/resources/$folder'
      preLoaderRoute: typeof ResourcesFolderRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/api/mail/$': {
      id: '/api/mail/$'
      path: '/api/mail/$'
      fullPath: '/api/mail/$'
      preLoaderRoute: typeof ApiMailSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AreasRouteChildren {
  AreasFolderRoute: typeof AreasFolderRoute
  AreasIndexRoute: typeof AreasIndexRoute
}

const AreasRouteChildren: AreasRouteChildren = {
  AreasFolderRoute: AreasFolderRoute,
  AreasIndexRoute: AreasIndexRoute,
}

const AreasRouteWithChildren = AreasRoute._addFileChildren(AreasRouteChildren)

interface ProjectsRouteChildren {
  ProjectsFolderRoute: typeof ProjectsFolderRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsFolderRoute: ProjectsFolderRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesFolderRoute: typeof ResourcesFolderRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesFolderRoute: ResourcesFolderRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  AreasRoute: AreasRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CaptureRoute: CaptureRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MailRoute: MailRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  TasksRoute: TasksRoute,
  WhiteboardsRoute: WhiteboardsRoute,
  ApiMailSplatRoute: ApiMailSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
